ext {
    extName = 'Moviz Land'
    extClass = '.Movizland'
    extVersionCode = 1
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(':lib:mixdropextractor'))
    implementation(project(":lib:voeextractor"))
    implementation(project(":lib:doodextractor"))
    implementation(project(":lib:streamwishextractor"))
}
